config/routes.rb
Rails.application.routes.draw do

  root to: "articles#index"    
  
  post '/sessions', to: 'sessions#create'
  put '/sessions', to: 'sessions#create'
  patch '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get 'sessions/new', to: 'sessions#new'

  resources :articles do
      resources :comments
  end
    
  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
   
   include Visible
   
   belongs_to :user
   alias_attribute :author, :user
   has_many :comments, dependent: :destroy
    
   validates :title, presence: true
   validates :body, presence: true, length: { minimum: 10 }
    
   VALID_STATUSES = ['public', 'private', 'archived']

   validates :status, inclusion: { in: VALID_STATUSES }


end

app/models/comment.rb
class Comment < ApplicationRecord

  include Visible
    
  belongs_to :article
  
  VALID_STATUSES = ['public', 'private', 'archived']

   validates :status, inclusion: { in: VALID_STATUSES }
end

app/models/concerns/visible.rb
module Visible
    def archived?
        status == 'archived'
    end
end

app/models/user.rb
class User < ApplicationRecord

    has_many :articles

    validates :name, presence: true
    validates :password, presence: true
    validates :username, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    before_action :set_user
    
    private
    
    def set_user
        if session.include?(:uid) != nil
            @current_user = User.find_by(id: session[:uid])
        end
    end
    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end
  
  def show
      @article = Article.find(params[:id])
  end

  def new
      @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.author = @current_user

    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

 def edit
    @article = Article.find(params[:id])
   end

   def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
   end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end
  
  private

  def article_params
    params.require(:article).permit(:title, :body, :status)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end

    private
       
    def comment_params
        params.require(:comment).permit(:author, :body, :status)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.find_by(username: user_params[:username])
    
    if @user and @user.password == user_params[:password]
      session[:uid] = @user.id
      redirect_to articles_path
    else
      @user = User.new
      @error = "Usuário ou senha inválidos"
      render 'new'
    end
  end
  
  def destroy
    session[:uid] = nil
    @user = nil
    redirect_to articles_path
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def date_format(date)
        date.strftime "%d/%m/%Y"
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
     <div>
       <%= form.label :title, 'Título' %><br>
       <%= form.text_field :title %>
       <% article.errors.full_messages_for(:title).each do |message| %>
         <div><%= message %></div>
       <% end %>
     </div>

     <div>
       <%= form.label :body, 'Conteúdo' %><br>
       <%= form.text_area :body, style: 'height: 300px; resize: none' %><br>
       <% article.errors.full_messages_for(:body).each do |message| %>
         <div><%= message %></div>
       <% end %>
     </div>
     
     
    <div>
     <%= form.label :status %><br>
     <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
    </div>


     <div>
       <%= form.submit %>
     </div>
   <% end %>

app/views/articles/edit.html.erb
<h2 class="red-text">Editar Artigo</h2>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h2 class="red-text">Artigos</h2>

<ul>
    <% @articles.each do |article| %>
        <% unless article.archived? %>
        <li>
            <div style="padding-bottom: 20px;">
            <%= link_to article.title, article %> 
            <span class="grey-text lighten-2" style="font-size: 10pt;">(<%= date_format article.created_at %>)</span> <br/>
            por: <small><%= article.author.name %></small>
            </div>
        </li>
        <% end %>
    <% end %>
</ul>

app/views/articles/new.html.erb
<h2 class="red-text">Novo Artigo</h2>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h2 class="red-text"><%= @article.title %></h2>

<% if @current_user and @current_user.id == @article.author.id %>

<%= link_to "Editar", edit_article_path(@article) %> |
<%= link_to "Excluir", article_path(@article),
                     method: :delete,
                     data: { confirm: "Realmente deseja remover este artigo?" } %>
                     
<% end %>


<p><%= raw @article.body.gsub("\n", "<br/>") %></p>


<br/>

<h6 class="grey-text">Author: <span class="red-text lighten-4"><%= @article.author.name %></span></h6>

<br/>

<% if @article.comments.count > 0 %>
<h5 class="red-text lighten-2">Comentários</h5>
<div style="width: 100%; height: 1px;" class="grey lighten-2"></div>
<%= render @article.comments %>
<% end %>

<div style="width: 100%; height: 1px;" class="grey lighten-2"></div>
<div class="row">
    <div class="col s12 m4 l4">
        <h5>Adicione um comentário</h5>
        <%= render 'comments/form' %>
    </div>
</div>

app/views/comments/_comment.html.erb
<div class="card">
    <div class="card-content">
        <span class="card-title grey-text">
            <i class="material-icons">account_box</i>
            <small>
                <span><%= comment.author %></span>
            </small>
        </span>
        <%= comment.body %>
    </div>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <p>
    <%= form.label :author %><br>
    <%= form.text_field :author %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <div>
     <%= form.label :status %><br>
     <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    
    <nav>
      <div class="nav-wrapper grey lighten-4">
        <%= link_to '#', class: 'brand-logo' do %>
          <%= image_tag image_path('logo-white.png'), width: '128px' %>
        <% end %>
        
        <div class="row">
          <div class="col l6 push-l2">
            <ul id="nav-mobile" class="left hide-on-med-and-down">
              <li class="<%= "active" if controller_name == "articles" %>"><a href="/articles" class="red-text active">Artigos</a></li>
              <li class="<%= "active" if controller_name == "users" %>"><a href="/users" class="red-text">Membros</a></li>
              <li><a href="https://guides.rubyonrails.org/getting_started.html" target="_blank" class="red-text">Sobre</a></li>
            </ul>
          </div>
          
          <div class="col l6 pull-l2">
            <ul id="nav-mobile" class="right hide-on-med-and-down">
              <% if @current_user %>
              <li><a href="/articles/new" class="red-text">Criar Novo Artigo</a></li>
              <li><a href="/logout" class="red-text active">Sair</a></li>
              <% else %>
              <li><a href="/sessions/new" class="red-text active">Entrar</a></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </nav>
        
    
    <div class="container">
      <%= yield %>  
    </div>
  </body>
</html>

app/views/users/index.html.erb
<h2 class="red-text">Membros</h2>

<ul>
    <table>
        <tr>
            <th>Nome</th>
            <th>E-Mail</th>
            <th>Membro desde</th>
        </tr>
    <% @users.each do |user| %>
        <tr>
            <td><%= link_to user.name, user %></td>
            <td><%= user.email %></td>
            <td><%= date_format user.created_at %></td>
        </li>
    <% end %>
    </table>
</ul>